/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) attitude_model_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {140, 1, 1};
static const casadi_int casadi_s1[3] = {1, 6, 1};

/* External functions */
int l4casadi_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* l4casadi_f:(i0[140])->(o0[1x6]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (l4casadi_f(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* attitude_dynamics:(i0[140])->(o0[1x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a001, a002, a003, a004, a005, a006;
  arg[1] = arg[0]? arg[0] + 0 : 0;
  res[1]=w+140;
  if (casadi_f1(arg+1, res+1, iw, w+146, 0)) return 1;
  a001 = w[140];
  a002 = w[141];
  a003 = w[142];
  a004 = w[143];
  a005 = w[144];
  a006 = w[145];
  if (res[0]!=0) res[0][0]=a001;
  if (res[0]!=0) res[0][1]=a002;
  if (res[0]!=0) res[0][2]=a003;
  if (res[0]!=0) res[0][3]=a004;
  if (res[0]!=0) res[0][4]=a005;
  if (res[0]!=0) res[0][5]=a006;
  return 0;
}

CASADI_SYMBOL_EXPORT int attitude_dynamics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int attitude_dynamics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int attitude_dynamics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void attitude_dynamics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int attitude_dynamics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void attitude_dynamics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void attitude_dynamics_incref(void) {
}

CASADI_SYMBOL_EXPORT void attitude_dynamics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int attitude_dynamics_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int attitude_dynamics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real attitude_dynamics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* attitude_dynamics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* attitude_dynamics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* attitude_dynamics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* attitude_dynamics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int attitude_dynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 146;
  return 0;
}

CASADI_SYMBOL_EXPORT int attitude_dynamics_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 146*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
